In [1]:
import pandas as pd

In [2]:
water_df = pd.read_csv('../SourceMaterial/Water_FINAL.csv')

/Users/josephgeglia/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (2,3,4,5,6,9,11,13,15,17,21,22,23,24,27,28,31,32,33,34,35,36,37,40,41,42,43,44,45,46,47,48,49,50,55,56,57,58,59,60,61,62,63,64,65,66) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
water_df.head()

,Unnamed: 0,Unnamed: 0.1,Agency,BiasPC,CloudCover,Comments,Cruise,Database,Date,FieldActivityEventType,...,Weather Conditions Yesterday,WindDirection,WindSpeed,state,Point,HUC12_,HUCNAME_,FIPS_,COUNTY_,STATE_
0,0,2143,NaN,NaN,NaN,NaN,NaN,CMC,04/28/2018,NaN,...,NaN,W,1-10 knots,MD,POINT (-75.93002800000002 39.480194),20600020206,Bohemia River,24015,Cecil County,MD
1,1,2145,NaN,NaN,NaN,NaN,NaN,CMC,04/28/2018,NaN,...,NaN,W,1-10 knots,MD,POINT (-75.902528 39.480444),20600020206,Bohemia River,24015,Cecil County,MD
2,2,2147,NaN,NaN,NaN,NaN,NaN,CMC,04/28/2018,NaN,...,NaN,S,1-10 knots,MD,POINT (-75.873639 39.466889),20600020206,Bohemia River,24015,Cecil County,MD
3,3,2151,NaN,NaN,NaN,NaN,NaN,CMC,04/28/2018,NaN,...,NaN,SW,1-10 knots,MD,POINT (-75.854444 39.454),20600020206,Bohemia River,24015,Cecil County,MD
4,4,2152,NaN,NaN,NaN,NaN,NaN,CMC,04/28/2018,NaN,...,NaN,SW,1-10 knots,MD,POINT (-75.84352800000001 39.463667),20600020206,Bohemia River,24015,Cecil County,MD

In [4]:
water_df.describe()

,Unnamed: 0,Unnamed: 0.1,FieldActivityRemark,GaugeHeight,HUC12,Latitude,Longitude,LowerPycnocline,MeasureValue,PrecisionPC,Pressure,SampleDepth,SampleId,TotalDepth,UpperPycnocline,HUC12_,FIPS_
count,2.708717e+06,2.708717e+06,0.0,99773.000000,2.444456e+06,2.708717e+06,2.708717e+06,424435.000000,2.708717e+06,0.0,74079.000000,2.704881e+06,2.708717e+06,2.105652e+06,424435.000000,2.708717e+06,2.708717e+06
mean,1.354358e+06,2.214989e+06,NaN,10.861847,2.070009e+10,3.843319e+01,-7.658405e+01,11.318739,1.490216e+01,NaN,754.894667,4.147473e+00,2.044871e+05,1.149991e+01,6.650813,2.069454e+10,3.578554e+04
std,7.819394e+05,1.525271e+06,NaN,353.141177,9.915505e+07,1.000394e+00,6.551539e-01,5.302668,7.579417e+01,NaN,28.707134,5.776304e+00,1.856555e+05,9.183738e+00,3.276481,1.031873e+08,1.344905e+04
min,0.000000e+00,0.000000e+00,NaN,-0.290000,2.040303e+10,3.674004e+01,-8.043708e+01,0.700000,-1.400000e+01,NaN,1.000000,-1.000000e-01,1.000000e+00,0.000000e+00,0.000000,2.040303e+10,1.000100e+04
25%,6.771790e+05,8.509090e+05,NaN,2.210000,2.060002e+10,3.763189e+01,-7.686761e+01,7.000000,1.000400e+00,NaN,751.000000,5.000000e-01,3.035200e+04,3.700000e+00,4.500000,2.060002e+10,2.401900e+04
50%,1.354358e+06,2.185441e+06,NaN,3.210000,2.070011e+10,3.839600e+01,-7.640131e+01,10.500000,7.700000e+00,NaN,758.000000,1.250000e+00,1.070730e+05,1.000000e+01,6.500000,2.070010e+10,2.404100e+04
75%,2.031537e+06,3.530615e+06,NaN,5.190000,2.080105e+10,3.899748e+01,-7.617466e+01,14.500000,1.333000e+01,NaN,763.000000,6.000000e+00,4.139770e+05,1.600000e+01,8.500000,2.080105e+10,5.110100e+04
max,2.708716e+06,4.897264e+06,NaN,35500.000000,2.080208e+10,4.280672e+01,-7.483524e+01,30.500000,2.977700e+04,NaN,787.000000,3.600000e+01,4.620910e+05,1.530000e+02,21.500000,2.080208e+10,5.407100e+04

In [5]:
column_names = []
for column in water_df.columns:
    column_names.append(column)
column_names

['Unnamed: 0',
 'Unnamed: 0.1',
 'Agency',
 'BiasPC',
 'CloudCover',
 'Comments',
 'Cruise',
 'Database',
 'Date',
 'FieldActivityEventType',
 'FieldActivityRemark',
 'FlowStage',
 'GaugeHeight',
 'GroupCode',
 'HUC12',
 'Lab',
 'Latitude',
 'Layer',
 'Longitude',
 'LowerPycnocline',
 'MeasureValue',
 'Method',
 'ModifiedDate',
 'Other Comments',
 'Other Conditions',
 'Parameter',
 'ParameterName_CBP',
 'ParameterName_CMC',
 'PrecipType',
 'PrecisionPC',
 'Pressure',
 'Problem',
 'Program',
 'Project',
 'Qualifier',
 'Rainfall',
 'Rainfall Within 24 Hours',
 'Rainfall Within 48 Hours',
 'SampleDepth',
 'SampleId',
 'SampleReplicateType',
 'SampleType',
 'Sea State',
 'Source',
 'Station',
 'StationCode',
 'StationName',
 'Stream Flow',
 'Tidal Stage',
 'TideStage',
 'TierLevel',
 'Time',
 'TotalDepth',
 'Unit',
 'UpperPycnocline',
 'Water Color',
 'Water Color Description',
 'Water Odor',
 'Water Odor Description',
 'Water Surfaces',
 'WaveHeight',
 'Weather Conditions Day Before Yesterday',
 'Weather Conditions Today',
 'Weather Conditions Yesterday',
 'WindDirection',
 'WindSpeed',
 'state',
 'Point',
 'HUC12_',
 'HUCNAME_',
 'FIPS_',
 'COUNTY_',
 'STATE_']

In [6]:
water_temps = water_df[['Date', 'ModifiedDate', 'HUCNAME_', 'Latitude', 'Longitude', 'Parameter', "ParameterName_CBP", 'ParameterName_CMC', 'MeasureValue']].loc[water_df['Parameter'].str.contains('WT')]
water_temps

,Date,ModifiedDate,HUCNAME_,Latitude,Longitude,Parameter,ParameterName_CBP,ParameterName_CMC,MeasureValue
14572,01/01/2012,2020-04-15T14:35:09.607,Hazel Run-Rappahannock River,38.289800,-77.481600,WT.8,WATER TEMPERATURE DEG,Water temperature,9.00
14573,01/01/2014,2020-03-10T11:04:49.987,Totuskey Creek,37.923634,-76.720680,WT.8,WATER TEMPERATURE DEG,Water temperature,6.00
14574,01/01/2014,2020-03-10T11:16:13.723,Totuskey Creek,37.886036,-76.736281,WT.8,WATER TEMPERATURE DEG,Water temperature,6.00
14575,01/01/2014,2020-03-10T11:04:35.813,Totuskey Creek,37.926034,-76.709080,WT.8,WATER TEMPERATURE DEG,Water temperature,6.00
14576,01/01/2014,2020-03-10T11:04:18.423,Totuskey Creek,37.912934,-76.657379,WT.8,WATER TEMPERATURE DEG,Water temperature,5.00
...,...,...,...,...,...,...,...,...,...
2708712,11/8/2016,NaN,Hampton Roads,36.904560,-76.338360,WTEMP,WATER TEMPERATURE DEG,NaN,17.15
2708713,11/8/2016,NaN,Hampton Roads,36.904560,-76.338360,WTEMP,WATER TEMPERATURE DEG,NaN,17.27
2708714,11/8/2016,NaN,Hampton Roads,36.904560,-76.338360,WTEMP,WATER TEMPERATURE DEG,NaN,16.06
2708715,11/8/2016,NaN,Hampton Roads,36.904560,-76.338360,WTEMP,WATER TEMPERATURE DEG,NaN,16.07
2708716,11/8/2016,NaN,Hampton Roads,36.904560,-76.338360,WTEMP,WATER TEMPERATURE DEG,NaN,17.24

In [7]:
ph_df = water_df[['Date', 'ModifiedDate', 'HUCNAME_', 'Latitude', 'Longitude', 'Parameter',"ParameterName_CBP", 'ParameterName_CMC', 'MeasureValue']].loc[water_df['Parameter'].str.contains("PH")]
ph_df.head()

,Date,ModifiedDate,HUCNAME_,Latitude,Longitude,Parameter,ParameterName_CBP,ParameterName_CMC,MeasureValue
15295,03/15/2018,2018-10-16T19:24:43.963,Lower Anacostia River,38.86972,-77.00292,PH.6,PH CORRECTED FOR TEMPERATURE (25 DEG C),pH,7.00
15296,04/16/2018,2018-10-16T19:37:08.757,Lower Anacostia River,38.86972,-77.00292,PH.6,PH CORRECTED FOR TEMPERATURE (25 DEG C),pH,7.00
15297,04/30/2018,2018-10-16T19:36:53.35,Lower Anacostia River,38.86972,-77.00292,PH.6,PH CORRECTED FOR TEMPERATURE (25 DEG C),pH,6.80
15298,06/29/2018,2018-10-24T10:51:47.923,Lower Anacostia River,38.86972,-77.00292,PH.6,PH CORRECTED FOR TEMPERATURE (25 DEG C),pH,6.75
15299,09/27/2018,2018-10-24T10:37:54.563,Lower Anacostia River,38.86972,-77.00292,PH.6,PH CORRECTED FOR TEMPERATURE (25 DEG C),pH,7.30

In [8]:
conductivity_df = water_df[['Date', 'ModifiedDate', 'HUCNAME_', 'Latitude', 'Longitude', 'Parameter',"ParameterName_CBP", 'ParameterName_CMC', 'MeasureValue']].loc[water_df['Parameter'].str.contains('CO')]

In [9]:
conductivity_df.head()

,Date,ModifiedDate,HUCNAME_,Latitude,Longitude,Parameter,ParameterName_CBP,ParameterName_CMC,MeasureValue
15360,01/09/2019,2020-03-24T09:49:40.857,Basin Run-Octoraro Creek,39.661800,-76.147400,CO.8,SPECIFIC CONDUCTIVITY,Conductivity,200.0
15361,01/09/2019,2020-03-24T09:49:40.17,Basin Run-Octoraro Creek,39.702983,-76.109467,CO.8,SPECIFIC CONDUCTIVITY,Conductivity,232.0
15362,01/09/2019,2020-03-24T09:49:38.873,Tweed Creek-Octoraro Creek,39.706667,-76.115556,CO.8,SPECIFIC CONDUCTIVITY,Conductivity,264.0
15363,01/09/2019,2020-03-24T09:49:39.513,Basin Run-Octoraro Creek,39.659947,-76.152979,CO.8,SPECIFIC CONDUCTIVITY,Conductivity,260.0
15364,01/14/2020,2020-03-24T09:46:42.623,Basin Run-Octoraro Creek,39.661800,-76.147400,CO.8,SPECIFIC CONDUCTIVITY,Conductivity,237.0

In [10]:
water_temps.to_csv('../SourceMaterial/water_temps.csv', index=False)
ph_df.to_csv('../SourceMaterial/ph.csv', index=False)
conductivity_df.to_csv('../SourceMaterial/conductivity.csv', index=False)